# Generated by Django 3.2.5 on 2021-12-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
