# Generated by Django 3.2.5 on 2021-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_user_current_club'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 3)), fields=('club', 'role'), name='one_owner_per_club'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(check=models.Q(('role__lte', 3)), name='role_upperbound'),
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
