# Generated by Django 3.2.5 on 2021-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211120_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(default='Beginner', max_length=520),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='personal_statement',
            field=models.CharField(default='This is a personal statement', max_length=520),
            preserve_default=False,
        ),
    ]
