# Generated by Django 3.2.5 on 2021-12-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_user_current_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
