# Generated by Django 3.2.5 on 2021-12-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211209_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
