# Generated by Django 3.2.5 on 2021-12-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_match_played'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament_entry',
            constraint=models.UniqueConstraint(fields=('participant', 'tournament'), name='unique_entry'),
        ),
        migrations.AlterModelTable(
            name='tournament_entry',
            table='tournament_entry',
        ),
    ]
