# Generated by Django 3.2.5 on 2021-11-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211121_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
